language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - PREFER="--prefer-lowest --prefer-stable"
    - PREFER=""

before_install:
  - composer self-update

install: composer update --prefer-dist $PREFER $COMPOSER_FLAGS

script:
  - composer check
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
