name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: Check
      uses: docker://composer:1.9.0
      run: |
        - ls -lha
        - composer install
        - composer check
    - name: Build coverage report
      run: |
        - ./vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)
